name: Service Metrics Aggregation

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  aggregate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Setup Firebase credentials
      run: |
        cd backend
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
        
    - name: Run aggregation
      run: |
        cd backend
        python aggregation_pipeline.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: backend/serviceAccountKey.json 