name: Service Metrics Aggregation

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  aggregate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Setup Firebase credentials
      run: |
        cd backend
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
        
    - name: Set interval start time (UTC, rounded down to 15 min)
      id: interval
      run: |
        export INTERVAL_START=$(date -u +"%Y-%m-%dT%H:%M:00Z" -d @$(( $(date +%s) / 900 * 900 )))
        echo "INTERVAL_START=$INTERVAL_START" >> $GITHUB_ENV

    - name: Run aggregation
      run: |
        cd backend
        python aggregation_pipeline.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: backend/serviceAccountKey.json
        TZ: UTC
        INTERVAL_START: ${{ env.INTERVAL_START }}
        
    - name: Show logs on failure
      if: failure()
      run: |
        echo "Aggregation failed. Check the logs above for details."
        echo "Common issues:"
        echo "- Missing Firebase credentials"
        echo "- Network connectivity issues"
        echo "- Firestore permissions" # Trigger schedule
