name: Bulk Complaints Ingestion

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Write Firebase credentials from secret
      run: |
        cd backend
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json

    - name: Run bulk complaints ingestion script
      run: |
        cd backend
        python bulk_complaints_to_firestore.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: backend/serviceAccountKey.json
        TZ: UTC

    - name: Show logs on failure
      if: failure()
      run: |
        echo "Ingestion failed. Check the logs above for details."
        echo "Common issues:"
        echo "- Missing Firebase credentials"
        echo "- Network connectivity issues"
        echo "- Firestore permissions" 